import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import { ApolloWrapper } from '@/lib/apolloWrapper'
import { UserNameCacheProvider } from '@/lib/contexts/UserNameCacheContext'
import { ExerciseCacheProvider } from '@/lib/contexts/ExerciseCacheContext'
import "./globals.css";


const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});


export const metadata: Metadata = {
  title: "ProofLift",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${raleway.variable} dark`} suppressHydrationWarning>
      <body className="font-sans antialiased">
        <ApolloWrapper>
          <UserNameCacheProvider>
            <ExerciseCacheProvider>
              {children}
            </ExerciseCacheProvider>
          </UserNameCacheProvider>
        </ApolloWrapper>
      </body>
    </html>
  );
}